from enum import Enum

class Connector(Enum):
    CHANGING = 'CHANGING'
    NOT_CONNECTED = 'NOT_CONNECTED'
    CONNECTED = 'CONNECTED'
    SEARCH_COMM = 'SEARCH_COMM'
    RCD_FAULT = 'RCD_FAULT'
    CHARGING = 'CHARGING'
    CHARGING_PAUSED = 'CHARGING_PAUSED'
    CHARGING_FINISHED = 'CHARGING_FINISHED'
    CHARGING_CANCELLED = 'CHARGING_CANCELLED'
    DISABLED = 'DISABLED'
    OVERHEAT = 'OVERHEAT'
    CRITICAL_TEMPERATURE = 'CRITICAL_TEMPERATURE'
    INITIALIZATION = 'INITIALIZATION'
    CABLE_FAULT = 'CABLE_FAULT'
    LOCK_FAULT = 'LOCK_FAULT'
    CONTACTOR_FAULT = 'CONTACTOR_FAULT'
    VENT_FAULT = 'VENT_FAULT'
    DC_ERROR = 'DC_ERROR'
    UNKNOWN = 'UNKNOWN'
    UNAVAILABLE = 'UNAVAILABLE'

class Mode(Enum):
    On = 'ALWAYS_ON'
    Off = 'ALWAYS_OFF'
    Schema = 'SCHEMA'

class PowerMode(Enum):
    On = 'ON'
    Off  = 'OFF'
    Unknown = 'UNKNOWN'